version: '3'

services:
  wp:
    image: wordpress:5.2.2-fpm-alpine
    container_name: wp-theme
    env_file: .env
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: "${DB_HOST}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
    networks:
      - theme

  db:
    image: mysql:8.0
    container_name: db-theme
    env_file: .env
    ports:
      - ${IP}:3306:3306
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    networks:
      - theme

  webserver:
    depends_on:
      - wp
    image: nginx:1.17.3-alpine
    container_name: webserver-theme
    env_file: .env
    restart: unless-stopped
    ports:
      - 8100:8080
      - 443:443
    volumes:
      - ./wp-app:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - theme

volumes:
  db_data:

networks:
  theme:
    driver: bridge
